service: cas360-rest-api-demo

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  stackName: cas360-rest-api-demo
  apiName: cas360-rest-api-demo

  logRetentionInDays: 1
  logs:
    restApi:
      level: INFO

  deploymentBucket:
    name: deployment.bglcorp.com.au

functions:
    getUser:
        handler: src/user.getUser
        events:
            - http:
                  path: user/{Id}
                  method: GET
                  cors: true
